/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ControlMeasure.graphql
 * @generated SignedSource<<a12671749db86c82eb21f0b0935d0df4>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type ControlMeasure = {|
  +temperature: ?number;
  +humidity: ?number;
  +pressure: ?number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "ControlMeasure",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "temperature",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "humidity",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "pressure",
      "storageKey": null
    }
  ],
  "type": "Measure"
};

module.exports = fragment;
