/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule HomeHome.graphql
 * @generated SignedSource<<bb2d5591c50e96c923dabcae51a0094d>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type HomeHome = {|
  +measures: ?$ReadOnlyArray<?{| |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "HomeHome",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Measure",
      "name": "measures",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "ControlMeasure",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Query"
};

module.exports = fragment;
